services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: ["start-dev"]
  
      

  db:
    image: "postgres:latest"
    ports:
      - "5555:5432"
    environment:
        DB_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "kvittr"